language: python

dist: xenial

# sudo false implies containerized builds
sudo: false

python:
  - 3.7

env:
  global:
    - PACKAGE_NAME="trio_inspector"

install:
- pip install .
- pip install mypy pytest pytest-trio

script:
- mypy $PACKAGE_NAME --ignore-missing-imports
- pytest
